easy_admin:
    site_name: 'ITK sites'

    design:
        assets:
            css:
                - 'bundles/easyadmin/bootstrap-all.css'
                - 'bundles/easyadminextension/stylesheet/full-width.css'
                - 'build/easy_admin.css'

            js:
                # By default, EasyAdminBundle embeds a limited version of Bootstrap JS.
                # For collapsible form filters to work, a full version should be added:
                - 'bundles/easyadmin/bootstrap-all.js'

        menu:
            - Website
            - Server
            - label: 'Export'
            - label: Website (csv)
              route: api_websites_get_collection
              params:
                  _format: csv
                  pagination: false

    formats:
        datetime: 'd/m/Y H:i:s'

    entities:
         Website:
             class: App\Entity\Website
             disabled_actions: ['new', 'edit', 'delete']
             list:
                 actions: ['show']
                 max_results: 300
                 # form_filters:
                 #     - property: server
                 #     - property: type
                 #       type_options:
                 #           choices_static_callback: [getValuesList, [type]]

                 filters: ['type', 'server']

                 fields:
                     - property: domain
                       template: easy_admin/Website/domain.html.twig
                     - property: server
                     # - property: documentRoot
                     - property: type
                     - property: version
                     - property: data
                       template: easy_admin/Website/data.html.twig
                     - property: updatedAt

             show:
                 fields:
                     - property: domain
                       template: easy_admin/Website/domain.html.twig
                     - property: server
                     - property: documentRoot
                     - property: type
                     - property: version
                     - property: git
                       template: easy_admin/Website/data/git.html.twig
                     - property: data
                       template: easy_admin/Website/data.html.twig
                     - property: updatedAt
                     - property: search

         Server:
             class: App\Entity\Server
             disabled_actions: ['delete']
             list:
                 filters: ['name']

                 actions: ['show']
                 max_results: 50
                 sort: [name, ASC]
                 fields:
                     - property: name
                       template: easy_admin/Server/name.html.twig
                     - property: data
                       template: easy_admin/Server/data.html.twig
                       sortable: false
                     - property: websites
                     - property: enabled
                     - property: updatedAt
                     - property: createdAt

             show:
                 max_results: 100
                 fields:
                     - property: name
                       template: easy_admin/Server/name.html.twig
                     - property: enabled
                     - property: data
                       template: easy_admin/Server/data.html.twig
                     - property: websites

             form:
                 fields:
                     - property: name
                     - property: enabled
