easy_admin:
    site_name: 'ITK sites'

    design:
        assets:
            css:
                - 'bundles/easyadmin/bootstrap-all.css'
            js:
                # By default, EasyAdminBundle embeds a limited version of Bootstrap JS.
                # For collapsible form filters to work, a full version should be added:
                - 'bundles/easyadmin/bootstrap-all.js'

    formats:
        datetime: 'd/m/Y H:i:s'

    entities:
         Website:
             class: App\Entity\Website
             disabled_actions: ['new', 'edit', 'delete']
             list:
                 actions: ['show']
                 max_results: 300
                 # form_filters:
                 #     - property: server
                 #     - property: type
                 #       type_options:
                 #           choices_static_callback: [getValuesList, [type]]

                 fields:
                     - property: domain
                       template: easy_admin/Website/domain.html.twig
                     - property: server
                     - property: documentRoot
                     - property: type
                     - property: version
                     - property: data
                       template: easy_admin/Website/data.html.twig
                     - property: updatedAt

             show:
                 fields:
                     - property: domain
                       template: easy_admin/Website/domain.html.twig
                     - property: server
                     - property: documentRoot
                     - property: type
                     - property: version
                     - property: data
                       template: easy_admin/Website/data.html.twig
                     - property: updatedAt

         Server:
             class: App\Entity\Server
             disabled_actions: ['delete']
             list:
                 actions: ['show']
                 max_results: 50
                 fields:
                     - property: name
                       template: easy_admin/Server/name.html.twig
                     - property: data
                       template: easy_admin/Server/data.html.twig
                       sortable: false
                     - property: websites
                     - property: enabled
                     - property: updatedAt
                     - property: createdAt

             show:
                 fields:
                     - property: name
                       template: easy_admin/Server/name.html.twig
                     - property: enabled
                     - property: data
                       template: easy_admin/Server/data.html.twig
                     - property: websites

             form:
                 fields:
                     - property: name
                     - property: enabled
