easy_admin:
  entities:
     Website:
       class: App\Entity\Website
       disabled_actions: ['new', 'edit', 'delete']
       list:
         actions: ['show']
         #   max_results: 50
         fields:
           - property: domain
             template: domain.html.twig
           - property: server
           - property: documentRoot
           - property: type
           - property: version
           - property: data
             template: data.html.twig
           - property: updatedAt

       show:
         fields:
           - property: domain
           - property: server
           - property: documentRoot
           - property: type
           - property: version
           - property: data
             template: data.html.twig
           - property: updatedAt
