easy_admin:
  site_name: 'ITK sites'

  entities:
     Website:
       class: App\Entity\Website
       disabled_actions: ['new', 'edit', 'delete']
       list:
         actions: ['show']
         max_results: 300
         fields:
           - property: domain
             template: domain.html.twig
           - property: server
           - property: documentRoot
           - property: type
           - property: version
           - property: data
             template: data.html.twig
           - property: updatedAt

       show:
         fields:
           - property: domain
           - property: server
           - property: documentRoot
           - property: type
           - property: version
           - property: data
             template: data.html.twig
           - property: updatedAt

     Server:
       class: App\Entity\Server
       disabled_actions: ['delete']
       list:
         actions: ['show']
         max_results: 50
         fields:
           - property: name
           - property: data
             template: data.html.twig
             sortable: false
           - property: websites
           - property: enabled
           - property: updatedAt

       show:
         fields:
           - property: name
           - property: enabled
           - property: data
             template: data.html.twig
           - property: websites

       form:
         fields:
           - property: name
           - property: enabled
