easy_admin:
    site_name: 'ITK sites'

    design:
        assets:
            css:
                - 'build/easy_admin.css'

        menu:
            - Website
            - Server
            - label: 'Misc'
            - Audience
            - label: 'Export'
            - label: Website (csv)
              route: api_websites_get_collection
              params:
                  _format: csv
                  pagination: false

    formats:
        datetime: 'd/m/Y H:i:s'

    entities:
         Website:
             class: App\Entity\Website
             disabled_actions: ['new', 'delete']
             list:
                 actions: ['show']
                 max_results: 300

                 dql_filter: 'entity.enabled = true'

                 filters: ['type', 'server', 'audiences']

                 fields:
                     - property: domain
                       template: easy_admin/Website/domain.html.twig
                     - property: server
                     # - property: documentRoot
                     - property: type
                       template: easy_admin/Website/list/filter.html.twig
                     - property: version
                     - property: audiences
                       template: easy_admin/Website/list/filter.html.twig
                     - property: comments
                       sortable: false
                       template: easy_admin/Website/list/comments.html.twig
                     - property: data
                       template: easy_admin/Website/data.html.twig
                     - property: updatedAt

             show:
                 fields:
                     - property: domain
                       template: easy_admin/Website/domain.html.twig
                     - property: server
                     - property: documentRoot
                     - property: type
                     - property: version
                     - property: audiences
                     - property: git
                       template: easy_admin/Website/data/git.html.twig
                     - property: data
                       template: easy_admin/Website/data.html.twig
                     - property: updatedAt
                     - property: search

             edit:
                 fields:
                     - property: domain
                       type_options:
                           disabled: true
                     - property: comments
                     - property: audiences
                       type_options:
                           expanded: true

         Server:
             class: App\Entity\Server
             disabled_actions: ['delete']
             list:
                 filters: ['enabled', 'name']

                 actions: ['show']
                 max_results: 100
                 sort: [name, ASC]
                 fields:
                     - property: name
                       template: easy_admin/Server/name.html.twig
                     - property: data
                       template: easy_admin/Server/data.html.twig
                       sortable: false
                     - property: websites
                     - property: enabled
                     - property: updatedAt
                     - property: createdAt

             show:
                 max_results: 100
                 fields:
                     - property: name
                       template: easy_admin/Server/name.html.twig
                     - property: enabled
                     - property: data
                       template: easy_admin/Server/data.html.twig
                     - property: websites
                     - property: search

             new:
                 fields:
                     - property: name
                     - property: enabled

             edit:
                 fields:
                     - property: name
                       type_options:
                           disabled: true
                     - property: enabled


         Audience:
             class: App\Entity\Audience
             disabled_actions: ['delete']

             form:
                 fields:
                     - property: id
                     - property: name
